name: phone_number_metadata
description: phone metadata from lib phone number as dart consts
version: 2.0.1
homepage: https://github.com/cedvdb/dart_phone_metadata

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
